# Generated by Django 4.0.4 on 2022-04-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
    ]
