# Generated by Django 4.0.4 on 2022-04-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_size_options_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
    ]
