# Generated by Django 4.0.4 on 2022-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
