# Generated by Django 4.0.4 on 2022-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
