# Generated by Django 4.0.4 on 2022-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new_arrivals',
            field=models.BooleanField(default=False),
        ),
    ]
