# Generated by Django 4.0.4 on 2022-04-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_products_is_best_seller_products_is_new_arrivals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров!'},
        ),
    ]
