# Generated by Django 4.0.4 on 2022-04-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_type_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории!'},
        ),
    ]
